word1=raw_input("Please enter an adjective: ")
word2=raw_input("Please enter an adjective: ")
word3=raw_input("Please enter an noun: ")
word4=raw_input("Please enter an noun: ")
word5=raw_input("Please enter a plural noun: ")
word6=raw_input("Please enter a game: ")
word7=raw_input("Please enter a plural noun: ")
word8=raw_input("Please enter a verb ending in ing: ")
word9=raw_input("Please enter a verb enging in ing: ")
word10=raw_input("Please enter a plural noun: " )
word11=raw_input("Please enter verb ending in ing: ")
word12=raw_input("Please enter a noun: ")
word13=raw_input("Please enter a plant: ")
word14=raw_input("Please enter a part of the body: ")
word15=raw_input("Please enter a place: ")
word16=raw_input("Please enter a verb ending in ing: ")
word17=raw_input("Please enter a adjective: ")
word18=raw_input("Please enter a number: ")
word19=raw_input("Please enter a plural noun: ")

print "A vacation is when you take a trip to some {} place with your {} family. Usually you go to some place that is near a/an {} or up on a/an {} . A good vacation place is one where you can ride {} or play {} or go hunting for {} . I like to spend my time {} or {} . When parents go on a vacation, they spend their time eating three {} a day, fathers play golf, and mothers sit around {} . Last summer, my little brother fell in a/an {} and got poison {} all over his {} . My family is going to (the) {} and I will practice {} . Parents need vacations more than kids because parents are always very {} and because they have to work {} hours every day all year making enough {} to pay for the vacation.".format(word1, word2, word3, word4, word5, word6, word7, word8, word9, word10, word11, word12, word13, word14, word15, word16, word17, word18, word19)
